// Quran Surah Data - 114 Surahs with Arabic names and transliteration
const SURAHS = [
  { number: 1, name: "الفاتحة", latin: "Al-Fatihah" },
  { number: 2, name: "البقرة", latin: "Al-Baqarah" },
  { number: 3, name: "آل عمران", latin: "Ali 'Imran" },
  { number: 4, name: "النساء", latin: "An-Nisa" },
  { number: 5, name: "المائدة", latin: "Al-Ma'idah" },
  { number: 6, name: "الأنعام", latin: "Al-An'am" },
  { number: 7, name: "الأعراف", latin: "Al-A'raf" },
  { number: 8, name: "الأنفال", latin: "Al-Anfal" },
  { number: 9, name: "التوبة", latin: "At-Tawbah" },
  { number: 10, name: "يونس", latin: "Yunus" },
  { number: 11, name: "هود", latin: "Hud" },
  { number: 12, name: "يوسف", latin: "Yusuf" },
  { number: 13, name: "الرعد", latin: "Ar-Ra'd" },
  { number: 14, name: "إبراهيم", latin: "Ibrahim" },
  { number: 15, name: "الحجر", latin: "Al-Hijr" },
  { number: 16, name: "النحل", latin: "An-Nahl" },
  { number: 17, name: "الإسراء", latin: "Al-Isra" },
  { number: 18, name: "الكهف", latin: "Al-Kahf" },
  { number: 19, name: "مريم", latin: "Maryam" },
  { number: 20, name: "طه", latin: "Ta-Ha" },
  { number: 21, name: "الأنبياء", latin: "Al-Anbiya" },
  { number: 22, name: "الحج", latin: "Al-Hajj" },
  { number: 23, name: "المؤمنون", latin: "Al-Mu'minun" },
  { number: 24, name: "النور", latin: "An-Nur" },
  { number: 25, name: "الفرقان", latin: "Al-Furqan" },
  { number: 26, name: "الشعراء", latin: "Ash-Shu'ara" },
  { number: 27, name: "النمل", latin: "An-Naml" },
  { number: 28, name: "القصص", latin: "Al-Qasas" },
  { number: 29, name: "العنكبوت", latin: "Al-'Ankabut" },
  { number: 30, name: "الروم", latin: "Ar-Rum" },
  { number: 31, name: "لقمان", latin: "Luqman" },
  { number: 32, name: "السجدة", latin: "As-Sajdah" },
  { number: 33, name: "الأحزاب", latin: "Al-Ahzab" },
  { number: 34, name: "سبأ", latin: "Saba" },
  { number: 35, name: "فاطر", latin: "Fatir" },
  { number: 36, name: "يس", latin: "Ya-Sin" },
  { number: 37, name: "الصافات", latin: "As-Saffat" },
  { number: 38, name: "ص", latin: "Sad" },
  { number: 39, name: "الزمر", latin: "Az-Zumar" },
  { number: 40, name: "غافر", latin: "Ghafir" },
  { number: 41, name: "فصلت", latin: "Fussilat" },
  { number: 42, name: "الشورى", latin: "Ash-Shura" },
  { number: 43, name: "الزخرف", latin: "Az-Zukhruf" },
  { number: 44, name: "الدخان", latin: "Ad-Dukhan" },
  { number: 45, name: "الجاثية", latin: "Al-Jathiyah" },
  { number: 46, name: "الأحقاف", latin: "Al-Ahqaf" },
  { number: 47, name: "محمد", latin: "Muhammad" },
  { number: 48, name: "الفتح", latin: "Al-Fath" },
  { number: 49, name: "الحجرات", latin: "Al-Hujurat" },
  { number: 50, name: "ق", latin: "Qaf" },
  { number: 51, name: "الذاريات", latin: "Adh-Dhariyat" },
  { number: 52, name: "الطور", latin: "At-Tur" },
  { number: 53, name: "النجم", latin: "An-Najm" },
  { number: 54, name: "القمر", latin: "Al-Qamar" },
  { number: 55, name: "الرحمن", latin: "Ar-Rahman" },
  { number: 56, name: "الواقعة", latin: "Al-Waqi'ah" },
  { number: 57, name: "الحديد", latin: "Al-Hadid" },
  { number: 58, name: "المجادلة", latin: "Al-Mujadila" },
  { number: 59, name: "الحشر", latin: "Al-Hashr" },
  { number: 60, name: "الممتحنة", latin: "Al-Mumtahanah" },
  { number: 61, name: "الصف", latin: "As-Saff" },
  { number: 62, name: "الجمعة", latin: "Al-Jumu'ah" },
  { number: 63, name: "المنافقون", latin: "Al-Munafiqun" },
  { number: 64, name: "التغابن", latin: "At-Taghabun" },
  { number: 65, name: "الطلاق", latin: "At-Talaq" },
  { number: 66, name: "التحريم", latin: "At-Tahrim" },
  { number: 67, name: "الملك", latin: "Al-Mulk" },
  { number: 68, name: "القلم", latin: "Al-Qalam" },
  { number: 69, name: "الحاقة", latin: "Al-Haqqah" },
  { number: 70, name: "المعارج", latin: "Al-Ma'arij" },
  { number: 71, name: "نوح", latin: "Nuh" },
  { number: 72, name: "الجن", latin: "Al-Jinn" },
  { number: 73, name: "المزمل", latin: "Al-Muzzammil" },
  { number: 74, name: "المدثر", latin: "Al-Muddaththir" },
  { number: 75, name: "القيامة", latin: "Al-Qiyamah" },
  { number: 76, name: "الإنسان", latin: "Al-Insan" },
  { number: 77, name: "المرسلات", latin: "Al-Mursalat" },
  { number: 78, name: "النبأ", latin: "An-Naba" },
  { number: 79, name: "النازعات", latin: "An-Nazi'at" },
  { number: 80, name: "عبس", latin: "'Abasa" },
  { number: 81, name: "التكوير", latin: "At-Takwir" },
  { number: 82, name: "الانفطار", latin: "Al-Infitar" },
  { number: 83, name: "المطففين", latin: "Al-Mutaffifin" },
  { number: 84, name: "الانشقاق", latin: "Al-Inshiqaq" },
  { number: 85, name: "البروج", latin: "Al-Buruj" },
  { number: 86, name: "الطارق", latin: "At-Tariq" },
  { number: 87, name: "الأعلى", latin: "Al-A'la" },
  { number: 88, name: "الغاشية", latin: "Al-Ghashiyah" },
  { number: 89, name: "الفجر", latin: "Al-Fajr" },
  { number: 90, name: "البلد", latin: "Al-Balad" },
  { number: 91, name: "الشمس", latin: "Ash-Shams" },
  { number: 92, name: "الليل", latin: "Al-Layl" },
  { number: 93, name: "الضحى", latin: "Ad-Duha" },
  { number: 94, name: "الشرح", latin: "Ash-Sharh" },
  { number: 95, name: "التين", latin: "At-Tin" },
  { number: 96, name: "العلق", latin: "Al-'Alaq" },
  { number: 97, name: "القدر", latin: "Al-Qadr" },
  { number: 98, name: "البينة", latin: "Al-Bayyinah" },
  { number: 99, name: "الزلزلة", latin: "Az-Zalzalah" },
  { number: 100, name: "العاديات", latin: "Al-'Adiyat" },
  { number: 101, name: "القارعة", latin: "Al-Qari'ah" },
  { number: 102, name: "التكاثر", latin: "At-Takathur" },
  { number: 103, name: "العصر", latin: "Al-'Asr" },
  { number: 104, name: "الهمزة", latin: "Al-Humazah" },
  { number: 105, name: "الفيل", latin: "Al-Fil" },
  { number: 106, name: "قريش", latin: "Quraysh" },
  { number: 107, name: "الماعون", latin: "Al-Ma'un" },
  { number: 108, name: "الكوثر", latin: "Al-Kawthar" },
  { number: 109, name: "الكافرون", latin: "Al-Kafirun" },
  { number: 110, name: "النصر", latin: "An-Nasr" },
  { number: 111, name: "المسد", latin: "Al-Masad" },
  { number: 112, name: "الإخلاص", latin: "Al-Ikhlas" },
  { number: 113, name: "الفلق", latin: "Al-Falaq" },
  { number: 114, name: "الناس", latin: "An-Nas" }
];

// Helper function to get surah by number
function getSurah(number) {
  return SURAHS.find(s => s.number === number);
}

// Helper function to get surah display name
function getSurahDisplay(number) {
  const surah = getSurah(number);
  return surah ? `${surah.number}. ${surah.latin}` : '';
}
